In [17]:
import pandas as pd

earthquakes = pd.read_csv("../../Data/Source/EarthQuakes/earthquakes_2023_global.csv")

In [20]:
earthquakes.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,26642.000000,26642.000000,26642.000000,26642.000000,25227.000000,25225.000000,24776.000000,26642.000000,25093.000000,26642.000000,24970.000000,25065.000000
mean,16.852798,-11.487497,67.491224,4.007395,42.571332,124.930971,2.692908,0.581575,7.017267,4.475056,0.122735,33.315939
std,30.389200,130.053399,116.762456,0.794423,37.662352,67.430145,4.043568,0.256276,4.072365,4.451649,0.102271,48.022567
min,-65.849700,-179.998700,-3.370000,2.600000,0.000000,8.000000,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000
25%,-6.415275,-149.608650,10.000000,3.220000,19.000000,73.000000,0.612000,0.410000,4.140000,1.848000,0.080000,10.000000
50%,18.884167,-64.811833,21.998000,4.300000,30.000000,111.000000,1.579000,0.590000,7.060000,2.019000,0.111000,18.000000
75%,41.827950,126.965100,66.833000,4.500000,52.000000,165.000000,3.172000,0.750000,9.730000,6.669000,0.150000,36.000000
max,86.593900,179.999400,681.238000,7.800000,423.000000,350.000000,50.820000,1.880000,99.000000,60.670000,4.490000,884.000000

In [21]:
cord=earthquakes.drop(["dmin","depth"],axis=1)

In [22]:
cord

,time,latitude,longitude,mag,magType,nst,gap,rms,net,id,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2023-01-01T00:49:25.294Z,52.0999,178.5218,3.10,ml,14.0,139.0,0.18,us,us7000j5a1,2023-03-11T22:51:52.040Z,"Rat Islands, Aleutian Islands, Alaska",earthquake,8.46,21.213,0.097,14.0,reviewed,us,us
1,2023-01-01T01:41:43.755Z,7.1397,126.7380,4.50,mb,32.0,104.0,0.47,us,us7000j3xk,2023-03-11T22:51:45.040Z,"23 km ESE of Manay, Philippines",earthquake,5.51,7.445,0.083,43.0,reviewed,us,us
2,2023-01-01T03:29:31.070Z,19.1631,-66.5251,3.93,md,23.0,246.0,0.22,pr,pr2023001000,2023-03-11T22:51:29.040Z,Puerto Rico region,earthquake,0.91,15.950,0.090,16.0,reviewed,pr,pr
3,2023-01-01T04:09:32.814Z,-4.7803,102.7675,4.30,mb,17.0,187.0,0.51,us,us7000j3xm,2023-03-11T22:51:45.040Z,"99 km SSW of Pagar Alam, Indonesia",earthquake,10.25,6.579,0.238,5.0,reviewed,us,us
4,2023-01-01T04:29:13.793Z,53.3965,-166.9417,3.00,ml,19.0,190.0,0.31,us,us7000j1zd,2023-03-11T22:51:38.040Z,"59 km SSW of Unalaska, Alaska",earthquake,1.41,1.999,0.085,18.0,reviewed,us,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26637,2023-12-29T03:37:19.334Z,-6.9527,154.9829,5.20,mb,72.0,60.0,0.93,us,us6000m0c5,2023-12-29T04:05:57.040Z,"89 km SW of Panguna, Papua New Guinea",earthquake,10.07,1.765,0.048,141.0,reviewed,us,us
26638,2023-12-29T04:38:54.109Z,32.3262,141.7386,5.10,mb,74.0,121.0,0.70,us,us6000m0ch,2023-12-29T10:59:44.533Z,"Izu Islands, Japan region",earthquake,9.17,1.870,0.042,187.0,reviewed,us,us
26639,2023-12-29T08:42:05.747Z,-7.2411,68.0663,5.10,mb,60.0,54.0,0.57,us,us6000m0dr,2023-12-29T08:57:05.040Z,Chagos Archipelago region,earthquake,8.02,1.792,0.090,40.0,reviewed,us,us
26640,2023-12-29T11:02:48.679Z,-19.1602,169.0428,4.70,mb,40.0,61.0,0.82,us,us6000m0e5,2023-12-29T11:22:46.040Z,"49 km NNW of Isangel, Vanuatu",earthquake,8.52,7.433,0.081,46.0,reviewed,us,us
26641,2023-12-29T16:31:16.656Z,25.1050,96.5309,5.00,mb,53.0,64.0,0.78,us,us6000m0f0,2023-12-29T16:45:27.040Z,"92 km WSW of Myitkyina, Myanmar",earthquake,7.85,1.876,0.071,64.0,reviewed,us,us

In [23]:
cord["nst"]=cord["nst"].fillna(method="bfill")

/var/folders/ph/83mp9vhd3vl_4_gpp0vqfqc40000gn/T/ipykernel_43992/3228245102.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cord["nst"]=cord["nst"].fillna(method="bfill")

In [24]:
cord["nst"].isnull().sum()

0

In [25]:
cord["gap"]=cord["gap"].fillna(method="ffill")

/var/folders/ph/83mp9vhd3vl_4_gpp0vqfqc40000gn/T/ipykernel_43992/4199379643.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cord["gap"]=cord["gap"].fillna(method="ffill")

In [26]:
cord["gap"].isnull().sum()

0

In [27]:
cord["gap"]

0        139.0
1        104.0
2        246.0
3        187.0
4        190.0
         ...
26637     60.0
26638    121.0
26639     54.0
26640     61.0
26641     64.0
Name: gap, Length: 26642, dtype: float64

In [28]:
cord["horizontalError"]=cord["horizontalError"].fillna(cord["horizontalError"].mean())

In [29]:
cord["horizontalError"].isnull().sum()

0

In [32]:
cord["magError"]=cord["magError"].fillna(cord["magError"].median())

In [33]:
cord["magError"].isnull().sum()

0